env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-refresh
  - '@typescript-eslint'
  - simple-import-sort
rules:
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react-refresh/only-export-components: warn
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
      destructuredArrayIgnorePattern: ^_
